remote_theme: pages-themes/architect@v0.2.0
title: [Hospitals in the major cities in Bavarian region]
description: [I decided that this blog will be about all the hospitals that are available in Bavarian region.
  As a student I always fear that I will have no clue about where hospitals can be, so while making this blog, I will also learn where they are for myself.
  I also chose to do this project as I am studying Health Informatics where Technology meets Medicine, hence why I can relate to this more.
  To make this blog something I can manage, I will only include hospitals from major cities in Bavaria instead of all the hospitals in Germany or even Bavaria.
  One difference I'll have that other websites similar to my blog concept doesnt have is that mine will include a bit more thorough information about the hospitals as well as images to show how they look like]


